pipeline {
    agent any
    tools {dockerTool "docker"}
    environment {
        DOCKERHUB_CREDENTIALS = credentials('nial-dockerhub-credentials')
        DOCKERHUB_REPO = 'nial538/newapi-api'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir ('newAPI') {
                    script {
                        dockerImage = docker.build("${DOCKERHUB_REPO}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'DOCKERHUB_CREDENTIALS') {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
